[project]
name = "bird-finder"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "librosa==0.11.0",
    "numpy==2.2.6",
    "opencv-python==4.12.0.88",
    "pyaudio==0.2.14",
    "tflite-runtime==2.14.0"
]

